[package]
name = "plot_polygons_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "plot_polygons_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module"] }
numpy = "0.27"
plotters = { version = "0.3", default-features = false, features = ["bitmap_backend", "bitmap_encoder"] }
